### ISSUE TITLE
Doesn't build on arm or aarch64

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gottcode.Tetzle#1]
Looks like the build is failing with gl stuff on arm and aarch64 https://flathub.org/builds/#/builders/2/builds/7896

Until all builds pass (or are disabled) the binaries don't actually get released.

**Comment by gottcode** [comment]
I see. Is there any way I can disable arm and aarch64? Tetzle doesn't support ARM.

**Comment by gottcode** [comment]
Builds disabled for arm and aarch64.

**Comment by jdolan** [comment]
Heh, sorry, but.. surprisingly this is one of the top Google results for "flathub disable aarch64." Do you mind sharing how you did this? I maintain an application that will also not build on aarch64 due to OpenGL 3.3 and other dependencies.

**Comment by gottcode** [comment]
Sure! All I did was add a file called ```flathub.json``` to the flathub repo with the contents:

```
{
	"skip-arches": ["arm", "aarch64"]
}
```

I removed the file when I added support for OpenGL ES.

**Comment by jdolan** [comment]
Thank you so much! 🥇
